### ISSUE TITLE
Could you please provide all preprocessed datasets?

### ISSUE THREAD

**Issue by vhientran** [NLP2CT/kNN-TL#1]
Hi @sudanl ,

Thanks so much for releasing the source code of your interesting paper. It seems that only the De-En dataset for the Parent model and the Tr-En dataset for Child model are available. If possible, please help to provide the download link of the remaining datasets (e.g., Fr-En for the Parent model; Id-En, Ca-En, and Hu-En for the Child model), as I am trying to reproduce all results reported in the paper.

Thank you very much for your time and your help!

**Comment by sudanl** [comment]
Hi vhientran,

Thank you for your interest in our work. The data of three low-resource language pairs comes from GlobalVoices and can be downloaded from this [link](https://data.statmt.org/smrt/). The Fr-En data can be downloaded and processed following this [link](https://github.com/facebookresearch/fairseq/blob/main/examples/translation/prepare-wmt14en2fr.sh).

**Comment by vhientran** [comment]
I will try. Thank you!
